openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of AquaTrack application for water intake tracking.
tags:
  - name: Water
    description: Operations related to managing water consumption.
  - name: User
    description: Operations related to managing users profiles.
servers:
  - url: http://localhost:3000
  - url: https://aqua-track-project-back.onrender.com
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /auth/total-users:
    get:
      $ref: ../swagger/paths/auth/get/total-users.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/get/get-oauth-url.yaml
  /auth/current-user:
    get:
      $ref: ../swagger/paths/auth/get/current-user.yaml
  /auth/update-user:
    patch:
      $ref: ../swagger/paths/auth/patch/update-user.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/post/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/post/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/post/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/post/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/post/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/post/reset-pwd.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
